name: MCDC Analysis

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  mcdc:
    name: Run MCDC Analysis
    uses: arielswalker/cFS/.github/workflows/mcdc-reusable.yml@test-cfs/workflows122