name: MCDC Coverage

on:
  workflow_call:
    inputs:
      # Optional inputs
      app-name:
        description: Application name, if different from repo name
        type: string
        required: false
        default: ''   

env:
  SIMULATION: native
  OMIT_DEPRECATED: true
  ENABLE_UNIT_TESTS: true
  CTEST_OUTPUT_ON_FAILURE: true
  
# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

jobs:
  # Checks for duplicate actions. Skips push actions if there is a matching or
  # duplicate pull-request action.
  checks-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  mcdc:
    needs: checks-for-duplicates
    if: ${{ needs.checks-for-duplicates.outputs.should_skip != 'true' || contains(github.ref, 'main') }}
    name: Build and Run MCDC
    runs-on: ubuntu-20.04
    container: ghcr.io/arielswalker/mcdc:latest

    steps:
    # Add to dockerfile
      - name: Set up dependencies 
        run: |
          apt-get update
          apt-get install -y git cmake lcov python3
          
      - name: Debug gcc
        run: |
          gcc -v
          gcov -v
          which gcc
          which gcov
            
      - name: Checkout Bundle Main
        uses: actions/checkout@v4
        with:
          submodules: true
          repository: arielswalker/cFS

      - name: Checkout Repo
        if: ${{ inputs.app-name != '' }}
        uses: actions/checkout@v4
        with:
          path: apps/${{ inputs.app-name }}

      - name: Copy Files
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs
       
      - name: Modify osal to include coverage flags
        run: |
          sed -i '/if (NOT CMAKE_CROSSCOMPILING AND NOT OSAL_OMIT_DEPRECATED)/,/\}/s/set(UT_COVERAGE_COMPILE_FLAGS.*/set(UT_COVERAGE_COMPILE_FLAGS -pg -O0 -fprofile-arcs -ftest-coverage -fcondition-coverage -fprofile-abs-path)/' osal/src/bsp/generic-linux/build_options.cmake
          sed -i '/if (NOT CMAKE_CROSSCOMPILING AND NOT OSAL_OMIT_DEPRECATED)/,/\}/s/set(UT_COVERAGE_LINK_FLAGS.*/set(UT_COVERAGE_LINK_FLAGS -pg -O0 -fprofile-arcs -ftest-coverage -fcondition-coverage -fprofile-abs-path)/' osal/src/bsp/generic-linux/build_options.cmake

      - name: Echo edited osal file
        run: |
          # Output the entire contents of osal/CMakeLists.txt to verify the changes
          ls
          pwd
          cat osal/src/bsp/generic-linux/build_options.cmake
          
      - name: Add repo to build
        if: ${{ inputs.app-name != '' }}
        run: echo 'set(MISSION_GLOBAL_APPLIST ${{ inputs.app-name }})' >> sample_defs/targets.cmake
        
      - name: Make prep
        run: make prep VERBOSE=1

      - name: Make install 
        if: ${{ inputs.app-name == '' }}
        run: make install VERBOSE=1

      - name: Make test 
        if: ${{ inputs.app-name == '' }}
        run: |
          echo "BASE_DIR=build/native/default_cpu1" >> $GITHUB_ENV
          (make test) | tee test_results.txt
        
      - name: Build app build dependencies
        if: ${{ inputs.app-name != '' }}
        run: make -C build/tools/elf2cfetbl

      - name: Build app target
        if: ${{ inputs.app-name != '' }}
        run: |
          make -C build/native/default_cpu1/apps/$APP_LOWER
          
      - name: Run app test
        if: ${{ inputs.app-name != '' }}
        run: |          
          echo "BASE_DIR=build/native/default_cpu1/apps/$APP_LOWER" >> $GITHUB_ENV
          (cd build/native/default_cpu1/apps/$APP_LOWER; ctest --verbose) | tee test_results.txt

      - name: Run mcdc analysis
        if: success() || failure()
        run: bash .github/scripts/mcdc-analyze.sh
        
# to do pull test modules 
# call script to show mcdc coverage 

# add gcov files and summary as archive 

      - name: Archive results
        # Upload if success or failure which supports skipping, unlike always()
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Unit test results
          path: |
            test_results.txt
            **/*.gcov
