name: MCDC Coverage

on:
  workflow_call:
    inputs:
      # Optional inputs
      app-name:
        description: Application name, if different from repo name
        type: string
        required: false
        default: ${{ github.event.repository.name }}      
      cache-key:
        description: Cache key to use
        type: string
        required: false
        default: ''

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

jobs:
  # Checks for duplicate actions. Skips push actions if there is a matching or
  # duplicate pull-request action.
  checks-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  mcdc:
    needs: checks-for-duplicates
    if: ${{ needs.checks-for-duplicates.outputs.should_skip != 'true' || contains(github.ref, 'main') }}
    name: Build and Run MCDC
    runs-on: ubuntu-20.04
    container: ghcr.io/arielswalker/mcdc:latest

    steps:
    # Add to dockerfile
      - name: Set up dependencies 
        run: |
          apt-get update
          apt-get install -y git cmake
      
      - name: Set up environment variables
        # Apps typically use lowercase targets and uppercase names, this logic is fragile but works
        run: |
          echo "APP_UPPER=$(echo ${{ inputs.app-name }} | sed 's/[a-z]/\U&/g')" >> $GITHUB_ENV
          echo "APP_LOWER=$(echo ${{ inputs.app-name }} | sed 's/[A-Z]/\L&/g')" >> $GITHUB_ENV

      - name: Get cache if supplied
        id: cache-src-bld
        if: ${{ inputs.cache-key != '' }}
        uses: actions/cache@v4
        with:
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/*
          key: ${{ inputs.cache-key }}

      - name: Checkout Bundle Main
        if: ${{ inputs.app-name != '' }}
        uses: actions/checkout@v4
        with:
          submodules: true
          repository: arielswalker/cFS

      - name: Checkout Repo
        if: ${{ inputs.app-name != '' }}
        uses: actions/checkout@v4
        with:
          path: apps/${{ inputs.app-name }}

      - name: Copy Files
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs

      - name: Add Repo To Build
        run: |
          sed -i "/list(APPEND MISSION_GLOBAL_APPLIST/a list(APPEND MISSION_GLOBAL_APPLIST $APP_LOWER)" sample_defs/targets.cmake

      - name: Make Prep
        run: make SIMULATION=native CC="gcc -O0 -fprofile-arcs --coverage -fcondition-coverage" CXX="g++  -O0 -fprofile-arcs --coverage -fcondition-coverage" ENABLE_UNIT_TESTS=true prep

      - name: Build app build dependencies
        run: make -C build/tools/elf2cfetbl

      - name: Build app target
        run: |
          make -C build/native/default_cpu1/apps/$APP_LOWER

      - name: Run test
        run: |
          (cd build/native/default_cpu1/apps/$APP_LOWER; ctest --verbose) | tee test_results.txt

      - name: Archive results
        # Upload if success or failure which supports skipping, unlike always()
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Unit test and coverage results
          path: |
            test_results.txt
